import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* this page is the global page and all the content inside it will be used for all the page */}
        <h1>this is the global layout</h1>
        {children}
      </body>
    </html>
  )
}
